org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Duser.home=C:/Users/ARNAV_TFS/Documents/Codex/2026-09-14/o-x20/work/user-home
android.useAndroidX=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kapt.use.worker.api=false
kapt.incremental.apt=false
android.suppressUnsupportedCompileSdk=35
